config/routes.rb
Rails.application.routes.draw do

  root    'homes#top'
  get     '/login', to: 'sessions#new'
  post    '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only:[:new, :create, :show, :edit, :update]
  resources :posts



  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user

  validates :place, presence: true
  validates :schedule, presence: true
  validates :body, presence: true
  validates :contact, presence: true


end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :posts, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # viewでもcontrollerのメソッドを使用できるように
  # helper_methodを
  helper_method :current_user

  private

  def current_user
    if session[:user_id]  #true = ログイン状態
       # ||=　変数に値がなければ代入する
       @current_user ||= User.find_by(id: session[:user_id])
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :user_login, only: [:new, :edit, :update, :destroy]
  before_action :set_futsal, only: [:edit, :update, :destroy]
  before_action :prevent_url, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = '投稿が完了しました'
      redirect_to posts_path
    else
      flash.now[:alert] = '投稿に失敗しました'
      render :new
    end
  end

  def index
    @user = current_user
    @posts = Post.all.order(created_at: :desc).page(params[:page]).per(10)

    if params[:search].present?
      @posts = Post.where('place LIKE ? or schedule LIKE ? or body LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%").page(params[:page]).per(10)
    end

  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = '内容を変更しました'
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end


  private

  def post_params
    params.require(:post).permit(:place, :schedule, :body, :contact)
  end

  # ログインしていないユーザーの利用制限
  def user_login
    unless current_user
      redirect_to root_path
    end
  end
  # ここまで

  # ログインユーザーのURL直打ち防止
  def set_futsal
    @post = Post.find(params[:id])
  end

  def prevent_url
    if @post.user_id != current_user.id
      redirect_to root_path
    end
  end
  # ここまで

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    # ログイン画面で入力されたアドレスでユーザー情報を探す
    user = User.find_by(email: session_params[:email])
    
    # 送られてきたパスワードによる認証をauthenticateメソッドを使って行う
    if user&.authenticate(session_params[:password])
      # 認証に成功できた場合、セッションにuser_idを格納する
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    reset_session  #セッション情報を削除
    redirect_to root_path
  end



  private

  def session_params
    params.permit(:email, :password)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :user_login, only: [:edit, :update]
  before_action :set_futsal, only: [:edit, :update]
  before_action :prevent_url, only: [:edit, :update]

  # ユーザー新規登録画面
  def new
    @user = User.new
  end

  # 新規登録
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc).page(params[:page]).per(10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'プロフィールを変更しました'
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end



  private

  def user_params
    params.require(:user).permit(:name, :email, :introduction, :password, :password_confirmation)
  end

  # ログインしていないユーザーの利用制限
  def user_login
    unless current_user
      redirect_to root_path
    end
  end
  # ここまで

  # ログインユーザーのURL直打ち防止
  def set_futsal
    @user = User.find(params[:id])
  end

  def prevent_url
    if @user.id != current_user.id
      redirect_to root_path
    end
  end
  # ここまで

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<div class="container">
  <div class="row d-flex justify-content-center text-center top-text">
    <h4>
      やりたい時にやりたい場所で！<br>
      気軽に個サルを楽しもう！
    </h4>
  </div>
  <div class="row d-flex justify-content-center mt-4">
    <%= link_to "個サルを探す", posts_path, class: "btn btn-info" %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<%= notice %>
<%= alert %>

app/views/layouts/_form.html.erb
<%= form_with url: posts_path, method: :get, local: true do |f| %>
  <%= f.text_field :search %>
  <%= f.submit '検索' %>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #D6E5DF;">
    <div class="navbar-brand m-auto">
      <%= link_to root_path do %>
        <h3>エンジョイ!!フットボール</h3>
      <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                   aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <!--ログインしているかどうか-->
        <% if current_user %>
          <li class="nav-item mr-3"><%= link_to "募集一覧", posts_path  %></li>
          <li class="nav-item mr-3"><%= link_to "新規募集", new_post_path  %></li>
          <li class="nav-item mr-3"><%= link_to "マイページ", user_path(current_user)  %></li>
          <li class="nav-item mr-3"><%= link_to "ログアウト", logout_path, method: :delete %></li>
        <% else %>
          <li class="nav-item mr-3"><%= link_to "募集一覧", posts_path %></li>
          <li class="nav-item mr-3"><%= link_to "チーム登録", new_user_path %></li>
          <li class="nav-item mr-3"><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
  <div class="d-flex justify-content-end mr-3">
    <%= render 'layouts/form' %>
  </div>
  <div class="d-flex justify-content-center">
    <%= render 'layouts/flash' %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>エンジョイ!!フットボール</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller.controller_name %>">
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
  <div class="d-flex justify-content-center mt-4">
    <h3>編集画面</h3>
  </div>
  <%= form_with model: @post, local: true do |f| %>
    <div class="form-group">
      <%= f.label :place, "会場" %>
      <%= f.text_field :place, autofocus: true, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :schedule, "開催日時" %>
      <%= f.text_field :schedule, autofocus: true, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :body, "詳細" %>
      <%= f.text_area :body, autofocus: true, size: '13x13', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :contact, "連絡URL" %>
      <%= f.text_field :contact, autofocus: true, class: 'form-control' %>
    </div>
    <div class="d-flex justify-content-center">
      <%= f.submit "変更を保存" %>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <h3 class="d-flex justify-content-center mt-4">
    募集チーム一覧
  </h3>
  <% @posts.each do |post| %>
    <div class="row d-flex justify-content-center mt-2 post-box">
      <div class="col-lg-3">
        <%= link_to user_path(post.user.id) do %>
          <%= post.user.name %>
        <% end %>
      </div>
      <div class="col-lg-3">
        会場:<br>
        <%= post.place %>
      </div>
      <div class="col-lg-3">
        <%= post.schedule %>
      </div>
      <div class="col-lg-3">
        <%= link_to "募集詳細", post_path(post.id) %>
      </div>
    </div>
  <% end %>
  <div class="row d-flex justify-content-center">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="d-flex justify-content-center mt-4">
    <h3>メンバーの募集をかけよう！</h3>
  </div>
  <%= form_with model: @post, local: true do |f| %>
    <div class="form-group">
      <%= f.label :place, "会場" %>
      <%= f.text_field :place, autofocus: true, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :schedule, "開催日時" %>
      <%= f.text_field :schedule, autofocus: true, placeholder: "○○月○○日（○）　○○時〜○○時", class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :body, "詳細" %>
      <%= f.text_area :body, autofocus: true, size: '10x10', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :contact, "連絡URL" %>
      <%= f.text_field :contact, autofocus: true, placeholder: "LabolaやオープンチャットのURL", class: 'form-control' %>
    </div>
    <div class="d-flex justify-content-center">
      <%= f.submit "投稿" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <h3 class="d-flex justify-content-center mt-4">
    個サル詳細
  </h3>
  <div class="row mt-4">
    <div class="col-lg-3">
      <%= link_to user_path(@user.id) do %>
        <%= @user.name %>
      <% end %>
    </div>
    <div class="col-lg-9">
      <div class="mb-3">
        会場：<%= @post.place %>
      </div>
      <div class="mb-3">
        日程：<%= @post.schedule %>
      </div>
      <div class="mb-3">
        内容：<br>
        <%= safe_join(@post.body.split("\n"),tag(:br)) %>
      </div>
      <div class="mb-3">
        連絡先：<%= link_to @post.contact, @post.contact %>
      </div>
      <% if @user == current_user %>
        <div>
          <%= link_to "編集", edit_post_path(@post.id), class: "btn btn-outline-dark" %>
          <%= link_to "削除", post_path(@post.id), method: :delete, class: "btn btn-outline-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="d-flex justify-content-center mt-4">
    <h3>プロフィール編集</h3>
  </div>
  <%= form_with model: @user, local: true do |f| %>
    <div class="form-group">
      <%= f.label :name, "チーム名" %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :introduction, "チーム紹介" %>
      <%= f.text_area :introduction, size: '15x15', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class="d-flex justify-content-center">
      <%= f.submit "変更を保存" %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="d-flex justify-content-center mt-4">
    <h3>新規登録</h3>
   </div>
  <%= form_with model: @user, local: true do |f| %>
    <div class="form-group">
      <%= f.label :name, "チーム名" %>
      <%= f.text_field :name, autofocus: true, placeholder: "チーム名", class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, autofocus: true, placeholder: "futsal@example.com", class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, autocomplete: "new-password", class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password, "パスワード（確認用）" %>
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: 'form-control' %>
    </div>
    <div class="d-flex justify-content-center">
      <%= f.submit "登録" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-lg-4">
      <h3>チームプロフィール</h3>
      <div class="team-name mt-3">
        チーム名：<b><%= @user.name %></b>
      </div>
      <% unless @user.introduction.nil? %>
        <div class="team-introduction mt-3">
          <%= safe_join(@user.introduction.split("\n"),tag(:br)) %>
        </div>
      <% end %>
      <% if @user == current_user %>
        <div>
          <%= link_to "プロフィール編集", edit_user_path(@user.id), class: "btn btn-outline-dark" %>
        </div>
      <% end %>
    </div>
    <div class="col-lg-8">
      <h3>募集日程</h3>
      <% @posts.each do |post| %>
        <div class="mt-3 post-box">
          <div>
            会場：<%= post.place %>
          </div>
          <div>
            日程：<%= post.schedule %>
            <%= link_to "募集詳細", post_path(post.id) %>
          </div>
        </div>
      <% end %>
      <div>
        <%= paginate @posts %>
      </div>
    </div>
  </div>
</div>